### ISSUE TITLE
Cannot open

### ISSUE THREAD

**Issue by flufylele** [mtricht/lunaris#56] opened 2020-01-25 20:12 UTC
Opening .bat and the cmd instantly closes. Tried run as admin but same issue.

**Comment by mtricht** [comment] 2020-01-25 21:04
@flufylele Open lunaris.bat with notepad and replace everything with:
`image\bin\java.exe -jar update4j.jar --remote https://raw.githubusercontent.com/mtricht/lunaris/master/autoupdater.xml --singleInstance`
Open lunaris.bat again, what do you see in the console?

**Comment by Purunts** [comment] 2020-01-26 03:50
Tried this, it updated, but the CMD isn't closing or minimizing onto the taskbar. If i close it lunaris also exits.

**Comment by flufylele** [comment] 2020-01-26 13:17
@mtricht Same thing. CMD starts, after 1 split second it makes the window verry small for the cmd then closes automatically.

**Comment by mordechaim** [comment] 2020-01-27 05:30
Subscribing to this thread to improve [update4j](https://github.com/update4j/update4j) in case it's the cause of this issue.

**Comment by mordechaim** [comment] 2020-01-27 17:08
It could be that it was downloading the new files but since it doesn't show progress you assumed it as stuck. Are you on a slow connection?

**Comment by mtricht** [comment] 2020-03-09 10:22
@mordechaim Do you have any suggestions on how we could use the update4j default bootstrap to show the update progress, but hide the console window once that's done?

**Comment by mordechaim** [comment] 2020-03-09 12:22
I'm not really sure as this is is dependent, but I think [this project](https://github.com/stirante/RuneChanger) successfully does just that. I think it involves subprocesses. 

Btw did you notice that the latest release of update4j now shows download progress? To update your existing clients simply list the new version and the startup script itself pointing to the new version in the config. For update4j just download it alongside the existing (don't try overwriting) but for the script keep the same name and overwrite.

**Closed** 2020-08-31 20:29 UTC
Labels: troubleshooting
