### ISSUE TITLE
Some custom hotkeys (especially CTRL + another key) don't work

### ISSUE THREAD

**Issue by LunarBear** [mtricht/lunaris#41] opened 2020-01-16 21:47 UTC
Hey,

Thank you for this great tool, the best PoETrade replacement among all the new ones imo.

I've been having one issue with custom hotkeys, I changed the default ones to CTRL + a letter (instead of ALT + a letter) and most of them don't work. CTRL+C works but CTRL+D, CTRL+E, CTRL+A... don't work. They either do nothing, or call the "item info" command (that I bound to CTRL+C). Odd.

I do not use the CTRL key in the game's settings, and I don't have any other tool / AHK script opened that could interfere. When I used CTRL + a letter with PoETradeMacro it worked well.

I switched back to ALT + a key and it works but I'm so used to CTRL+ a key that I would really like to use this key combo.

Thanks!

**Comment by pvaass** [comment] 2020-01-16 22:08
Hey! Thanks for the kinds words and the bug report!

My theory is that your bind of ctrl+c conflicts with the other bindings you set. Because the only way for us to get your item info is to actually press ctrl+c real fast, there's going to be an issue if you then actually bind ctrl+c to something:

Normal flow:
- Ctrl+D (e.g. search on /trade)
- App does ctrl+c real fast
- Parses the item and searches on /trade

Your flow (when Ctrl+C is binded to item info):
- Ctrl+D
- App does ctrl+c real fast
- Ctrl+C? That must mean we need item info. Let's discard your previous command (Ctrl+D)
- App does ctrl+c real fast (again)
- App shows item info

Can you try unbinding Ctlr+C and see if the rest of the keybinds work?

In the meantime, I'll check if we can solve the ctrl+c bind in the code somehow

Cheers!

**Comment by LunarBear** [comment] 2020-01-16 22:43
Okay, I tried different things to reproduce the bug, here's what I found:
- Whatever my hotkeys are (I set them back to the default ALT + something), when I press CTRL+C in game while hovering over an item, all the Lunaris hotkeys stop working
- Only way to get the hotkeys to work again is to relaunch the soft OR reassign any hotkey (even to the same one it was assigned to before) in Lunaris settings
- If I press CTRL+C outside of the game, the hotkeys don't break
- If i press CTRL+C in game but NOT hovering over an item, they don't break
So even unbinding my custom CTRL+C Lunaris hotkey, if I CTRL+C by mistake or if I actually want to copy the info of an item it breaks Lunaris hotkeys.

**Comment by mtricht** [comment] 2020-01-17 00:51
@LunarBear We've just pushed an update (v0.4.1) which fixes Lunaris breaking after pressing CTRL + C. You still can't use CTRL + C as a key bind, we'll look into that later. Can you let us know if it's working as intended now?

**Comment by LunarBear** [comment] 2020-01-17 16:50
Thanks, works great now!

**Comment by pvaass** [comment] 2020-01-17 21:42
@LunarBear Created a new issue for just the Ctrl+C bind: https://github.com/mtricht/lunaris/issues/42. Closing this one!

**Closed** 2020-01-17 21:42 UTC
Labels: bug
